### ISSUE TITLE
hi，i want to rotate the video when collage

### ISSUE THREAD

**Issue by hydyy** [Onix-Systems/video-maker#17]
i want rotate the video , but when i use imageByCroppingToRect to do that , i can do it!

this is my code 
![image](https://cloud.githubusercontent.com/assets/1254987/21935346/248aca68-d9e8-11e6-8276-2130269c5fe9.png)

i realy need help! so please help me ! thx very very mach!!!

**Comment by derpoliuk** [comment]
@hydyy did you managed to fix your issue? If yes, what was the problem?

**Comment by hydyy** [comment]
@derpoliuk  I'm doing a feature to rotate the video during the collage, i already finish it!  no problem!
but i has other problem ..

when i collage the video 

Error Domain=AVFoundationErrorDomain Code=-11841 "操作停止" UserInfo={NSLocalizedDescription=操作停止, NSLocalizedFailureReason=未能创作视频。}) 

what's the mean?

**segment**
![image](https://cloud.githubusercontent.com/assets/1254987/22016288/b6bb2324-dce0-11e6-865f-739075209743.png)

**video register**
![image](https://cloud.githubusercontent.com/assets/1254987/22016303/c7545eee-dce0-11e6-9c97-f08cef698590.png)

**Comment by hydyy** [comment]
@derpoliuk

**Comment by derpoliuk** [comment]
@hydyy I don't know the code and I don't know how exactly you're using Movie Maker. 

But hopefully these 2 SO questions will set you on the right track:

* http://stackoverflow.com/questions/31092455/avassetexportsession-export-fails-non-deterministically-with-error-operation-s
* http://stackoverflow.com/questions/12856488/averrorinvalidvideocomposition-11841

It seems that you're having similar issue.

**Comment by hydyy** [comment]
ok, thx , i will try it.
