### ISSUE TITLE
why not support ios8.0?

### ISSUE THREAD

**Issue by hydyy** [Onix-Systems/video-maker#18]
~~~~~

**Comment by derpoliuk** [comment]
As a general rule, we  support current iOS release and previous one.

**Comment by hydyy** [comment]
ok~ thx


原始邮件
发件人:Stanislav Derpoliuknotifications@github.com
收件人:Onix-Systems/ios-video-makerios-video-maker@noreply.github.com
抄送:Adamhouyaodong@qq.com; Authorauthor@noreply.github.com
发送时间:2017年1月17日(周二) 18:36
主题:Re: [Onix-Systems/ios-video-maker] why not support ios8.0? (#18)


As a general rule, we support current iOS release and previous one.

**Comment by derpoliuk** [comment]
@hydyy I'm closing this one. Feel free to reopen.

**Comment by hydyy** [comment]
@derpoliuk I am test on ios8, when the preview collage will be Caton, you know why this is it?
